version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: integration
  reviewers:
  - daveh1234321
  ignore:
  - dependency-name: aws-amplify-react
    versions:
    - 4.2.17
    - 4.2.19
  - dependency-name: "@aws-amplify/ui-react"
    versions:
    - 0.2.33
    - 0.2.35
  - dependency-name: aws-amplify
    versions:
    - 3.3.13
    - 3.3.15
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.0
    - 12.6.2
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.2
    - 11.2.3
  - dependency-name: react-table
    versions:
    - 7.6.2
  - dependency-name: react-scripts
    versions:
    - 4.0.1
  - dependency-name: "@date-io/moment"
    versions:
    - 2.10.6
